name: Update icons
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1-5'

jobs:
  update-icons:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'update-icons'

      - uses: actions/checkout@v2
        with:
          ref: 'update-icons'
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Export icons from Figma
        run: ./tools/export-icons.sh
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --ignore-submodules --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit changes, if any
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin
          git add .
          git commit -am "Pull icon updates from figma" || true
          git push origin update-icons || true

      - name: Create PR if it doesn't exist
        if: steps.git-check.outputs.modified == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $(gh pr list --json "url" -q ".[].url" --head update-icons | wc -c) -eq 0 ]]; then
            gh pr create --base main --head update-icons --title "Sync icon updates from figma" --body "This PR is generated by 'update-icons.yaml' when icon changes are made to tokens.json"
          fi
